#! /bin/sh

# Mount pseudo file systems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts devpts /dev/pts
#mount -t tmpfs tmpfs /var
#mount -t tmpfs tmpfs /tmp

# Set up the hostname
hostname miniroot

# Start services
#/etc/rc.udhcpc start
#/etc/rc.telnetd start
