# options can be set in config.mk
DROPBEAR_SRC ?= 0.52
DROPBEAR_PATCH_DIR =
#DROPBEAR_BUILD_INSIDE = no

# if DROPBEAR_SRC is a version number
ifeq ($(strip $(shell $(TOOLS_DIR)/is_src.sh '$(DROPBEAR_DIR)' '$(DROPBEAR_SRC)')),false)
override DROPBEAR_SRC := dropbear-$(strip $(DROPBEAR_SRC)).tar.bz2
DROPBEAR_URL = http://matt.ucc.asn.au/dropbear/releases/$(DROPBEAR_SRC)
endif

DROPBEAR_SRC_DIR = $(shell $(TOOLS_DIR)/get_src_dir.sh '$(DROPBEAR_DIR)' '$(DROPBEAR_SRC)')
DROPBEAR_BUILD_DIR = $(if $(DROPBEAR_BUILD_INSIDE), $(DROPBEAR_SRC_DIR), $(BUILD_DIR)/$(notdir $(DROPBEAR_SRC_DIR)))
DROPBEAR_BUILD_CONFIG = $(DROPBEAR_SRC_DIR)/options.h
DROPBEAR_BUILD_BIN = $(DROPBEAR_BUILD_DIR)/dropbearmulti
DROPBEAR_INSTALL_DIR = $(ROOT_BUILD_DIR)/usr/sbin
DROPBEAR_INSTALL_BIN = $(DROPBEAR_INSTALL_DIR)/dropbearmulti
DROPBEAR_INSTALL_TOOLS_DIR = $(ROOT_BUILD_DIR)/usr/bin
DROPBEAR_INSTALL_CLIENT1_BIN = $(DROPBEAR_INSTALL_TOOLS_DIR)/dbclient
DROPBEAR_INSTALL_CLIENT2_BIN = $(DROPBEAR_INSTALL_TOOLS_DIR)/ssh
DROPBEAR_INSTALL_KEYGEN_BIN = $(DROPBEAR_INSTALL_TOOLS_DIR)/dropbearkey

.PHONY: dropbear dropbear_init dropbear_clean
$(eval $(call PKG_INCLUDE_RULE, $(PKG_DROPBEAR_SERVER) $(PKG_DROPBEAR_CLIENT), dropbear))

dropbear: $(DROPBEAR_INSTALL_BIN)

dropbear_init:
	@ echo '=== DROPBEAR ==='
	@ $(TOOLS_DIR)/init_src.sh '$(DROPBEAR_DIR)' '$(DROPBEAR_SRC)' '$(DROPBEAR_URL)' '$(DROPBEAR_PATCH_DIR)'

define DROPBEAR_DISABLE_FEATURE
sed -i 's,^\(#define.*$(1).*\),/*\1*/,' $(DROPBEAR_BUILD_CONFIG)
endef

$(DROPBEAR_BUILD_DIR)/Makefile:
	mkdir -p $(DROPBEAR_BUILD_DIR)
	( cd $(DROPBEAR_BUILD_DIR) && \
		$(SET_CROSS_PATH) $(abspath $(DROPBEAR_SRC_DIR))/configure $(CONFIGURE_CROSS_HOST) \
			--disable-lastlog \
	)
	$(call DROPBEAR_DISABLE_FEATURE, DROPBEAR_BLOWFISH)
	$(call DROPBEAR_DISABLE_FEATURE, DROPBEAR_TWOFISH)
	$(call DROPBEAR_DISABLE_FEATURE, DROPBEAR_MD5_HMAC)
	$(call DROPBEAR_DISABLE_FEATURE, ENABLE_.*FWD)
	$(call DROPBEAR_DISABLE_FEATURE, DO_MOTD)

$(DROPBEAR_BUILD_BIN): dropbear_init $(DROPBEAR_BUILD_DIR)/Makefile
	$(SET_CROSS_PATH) $(MAKE) -C $(DROPBEAR_BUILD_DIR) \
	$(SET_CROSS_COMPILE) $(SET_CROSS_CC) $(SET_CROSS_CFLAGS) \
	MULTI=1 PROGRAMS=' \
		$(if $(call PKG_IS_SET, $(PKG_DROPBEAR_SERVER)), dropbear dropbearkey) \
		$(if $(call PKG_IS_SET, $(PKG_DROPBEAR_CLIENT)), dbclient) '

$(DROPBEAR_INSTALL_BIN): $(DROPBEAR_BUILD_BIN)
	mkdir -p $(DROPBEAR_INSTALL_DIR)
	cp $(DROPBEAR_BUILD_BIN) $(DROPBEAR_INSTALL_BIN)
	$(CROSS_STRIP) $(DROPBEAR_INSTALL_BIN)
	mkdir -p $(DROPBEAR_INSTALL_TOOLS_DIR)
	$(if $(call PKG_IS_SET, $(PKG_DROPBEAR_SERVER)), \
		ln -snf $(DROPBEAR_INSTALL_BIN) $(DROPBEAR_INSTALL_KEYGEN_BIN) )
	$(if $(call PKG_IS_SET, $(PKG_DROPBEAR_CLIENT)), \
		ln -snf $(DROPBEAR_INSTALL_BIN) $(DROPBEAR_INSTALL_CLIENT1_BIN) && \
		ln -snf $(DROPBEAR_INSTALL_BIN) $(DROPBEAR_INSTALL_CLIENT2_BIN) )

dropbear_clean:
	- $(DROPBEAR_MAKE) clean
	- rm -f $(DROPBEAR_INSTALL_BIN)
	- rm -f $(DROPBEAR_INSTALL_KEYGEN_BIN)
	- rm -f $(DROPBEAR_INSTALL_CLIENT1_BIN)
	- rm -f $(DROPBEAR_INSTALL_CLIENT2_BIN)
