#! /bin/sh

# This script is intended to help investigating miniroot.
# e.g. it can help to find where a variable is used.

print_usage () {
	echo "usage: $(basename $0) <grep-pattern>"
	exit $1
}

COLOR_RESET='[0m'
COLOR_FILE='[1m'
COLOR_LINE='[4m'
COLOR_PATTERN='[7m'

find_in_dir () {
	DIR=$1
	shift
	find -L $DIR -maxdepth 3 |
	fgrep -v 'CVS/' |
	fgrep -v '.svn/' |
	fgrep -v '.git/' |
	grep '\([Mm]akefile.*\|\.\(mk\|sh\)\)$' |
	xargs grep -n --color=never "$*" |
	sed "s,^$DIR/,," |
	sed 's,^\./,,' |
	sed "s,\([^/:]*\):[	 ]*\([0-9]*\):[	 ]*,$COLOR_FILE\1$COLOR_RESET $COLOR_LINE+\2$COLOR_RESET ," |
	sed "s,\($*\),$COLOR_PATTERN\1$COLOR_RESET,g"
}

if [ -z "$*" ] ; then
	print_usage 1
fi
if [ "$*" = '-h' ] ; then
	print_usage 0
fi

find_in_dir $(dirname $0)/.. $*
