#! /bin/sh

# This script is intended to help investigating miniroot.
# e.g. it can help to find where a variable is used.

print_usage () {
	echo "usage: $(basename $0) <grep-pattern>"
	exit $1
}

COLOR_RESET='[0m'
COLOR_FILE='[1m'
COLOR_LINE='[4m'
COLOR_PATTERN='[7m'

find_in_dir () {
	DIR=$1
	shift
	VARS=$(make -sC $DIR 'DL_DIR?' 'SRC_DIR?' 'BUILD_DIR?')
	DL_DIR=$(echo "$VARS" | sed -n 's,^DL_DIR = ,,p')
	SRC_DIR=$(echo "$VARS" | sed -n 's,^SRC_DIR = ,,p')
	BUILD_DIR=$(echo "$VARS" | sed -n 's,^BUILD_DIR = ,,p')
	find -L $DIR \
		-regextype posix-extended \
		\( \
			-path "$DIR/$DL_DIR" -o \
			-path "$DIR/$SRC_DIR" -o \
			-path "$DIR/$BUILD_DIR" -o \
			-path '*/CVS' -o \
			-path '*/.svn' -o \
			-path '*/.hg' -o \
			-path '*/.git' \
		\) -prune -o \
		-type f \
		-regex '.*/([Mm]akefile.*|.*\.(mk|sh))' \
		-exec grep -n --color=never "$*" '{}' + |
	sed "s,^$DIR/,," |
	sed 's,^\./,,' |
	sed "s,\([^/:]*\):[	 ]*\([0-9]*\):[	 ]*,$COLOR_FILE\1$COLOR_RESET $COLOR_LINE+\2$COLOR_RESET ," |
	sed "s,\($*\),$COLOR_PATTERN\1$COLOR_RESET,g"
}

if [ -z "$*" ] ; then
	print_usage 1
fi
if [ "$*" = '-h' ] ; then
	print_usage 0
fi

find_in_dir $(dirname $0)/.. "$*"
